environment:
  matrix:
    - node_version: '8'
    - node_version: '9'
    - node_version: '10'

install:
  - ps: 'Install-Product node $env:node_version'
  - ps: $Env:PATH += ';C:\msys64\mingw64\bin'
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/x86_64
  # - rustup-init.exe -y --default-host x86_64-pc-windows-gnu --default-toolchain stable
  - rustup-init.exe -y --default-host i386-pc-windows-msvc --default-toolchain stable
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -Vv
  - node -v
  - npm -v
  - yarn global add yarn@latest
  - yarn

test_script:
  - yarn test

before_deploy:
  - yarn package

cache:
  - C:\Users\appveyor\.cargo\registry
  - native/target

# Building is done in the test phase, so we disable Appveyor's build phase.
build: false

notifications:
  - provider: Email
    on_build_success: false
