environment:
  matrix:
    - node_version: '8'
    - node_version: '9'
    - node_version: '10'

install:
  - ps: 'Install-Product node $env:node_version'
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -Vv
  - node -v
  - npm -v
  - yarn global add yarn@latest
  - yarn

test_script:
  - yarn test

before_deploy:
  - yarn package

cache:
  - C:\Users\appveyor\.cargo\registry
  - native/target

# Building is done in the test phase, so we disable Appveyor's build phase.
build: false

notifications:
  - provider: Email
    on_build_success: false
